name: CI

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        strategy:
            matrix:
                node-version: [12]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install
              working-directory: ${{env.working-directory}}

            - name: Build
              run: npm run build
              working-directory: ${{env.working-directory}}

            - name: Push build
              run: |
                  git_setup() {
                    cat <<- EOF > $HOME/.netrc
                      machine github.com
                      login $GITHUB_ACTOR
                      password $GITHUB_TOKEN
                      machine api.github.com
                      login $GITHUB_ACTOR
                      password ${{ secrets.GITHUB_TOKEN }}
                  EOF
                    chmod 600 $HOME/.netrc

                    git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
                    git config --global user.name "$GITHUB_ACTOR"
                  }

                  git_setup
                  git remote update
                  git add -f ./client/build 
                  git commit -m "Auto Build"
                  git push --set-upstream origin "build"
