name: CI

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        strategy:
            matrix:
                node-version: [12]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install
              working-directory: ${{env.working-directory}}

            - name: Build
              run: npm run build
              working-directory: ${{env.working-directory}}

            - name: Push build
              run: |
                  git config --global user.name 'ChaitanyaLKulkarni'
                  git config --global user.email 'ChaitanyaLKulkarni@users.noreply.github.com'
                  git add -f ./client/build
                  git commit -am "Automated Build"
                  #git push
            - name: Push To Heroku
              run: |
                  git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
                  git fetch --all --unshallow
                  git filter-branch -- --all
                  git push heroku main --force
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
